<?php

namespace JSP\CoreBundle\Repository;

/**
 * AccessKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
