<?php

namespace MGC\TimeTrackingBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository {

    public function countAll() {
        $queryBuilder = $this->createQueryBuilder('e');

        $queryBuilder->select('COUNT(e) AS nb');
        $result = $queryBuilder->getQuery()->getOneOrNullResult();
        $count = $result['nb'];

        return $count;
    }

}
