<?php

namespace MGC\Modules\Admin\PermissionBundle\Repository;

/**
 * PermissionHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
