admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

developer:
    resource: "@DeveloperBundle/Controller/"
    type:     annotation
    prefix:   /

todo:
    resource: "@TodoBundle/Controller/"
    type:     annotation
    prefix:   /

jsp_admin:
    resource: "@JspAdminBundle/Controller/"
    type:     annotation
    prefix:   /

jsp_core:
    resource: "@JspCoreBundle/Controller/"
    type:     annotation
    prefix:   /