services:
#    admin.example:
#        class: JSP\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    jsp.admin.service.element:
        class: JSP\AdminBundle\Services\ElementService
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@jsp.admin.mapper.element'

    jsp.admin.mapper.element:
        class: JSP\AdminBundle\Services\Mappers\ElementMapper