website:
  name: 'Back Office'
  #url: 'http://mgc.alexandre-dupre.fr'
  url: 'localhost'
  namespace: mgc
  modules:
    -
      name: administration
      uri: admin
      active: true
      order: 0
      group: admin
      permissions:
        -
          name: allow_access
          var: ''
          params: ''
          category: admin
          active: true
          order: 0